# Generated by Django 2.0.4 on 2018-04-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_delete_session_cart'),
        ('online_shop', '0002_auto_20180421_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('books', models.ManyToManyField(blank=True, to='main_site.Book')),
            ],
        ),
    ]
