# Generated by Django 2.0.4 on 2018-04-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_remove_session_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_cart',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
