# Generated by Django 2.0.4 on 2018-04-26 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_shop', '0007_auto_20180426_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_cart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='session_cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session_cart',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
