# Generated by Django 2.0.4 on 2018-04-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0008_auto_20180426_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_cart',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='session_cart',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='main_site.Book'),
        ),
    ]
