# Generated by Django 2.0.4 on 2018-04-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre_nom', models.CharField(max_length=100)),
                ('livre_auteur', models.CharField(max_length=100)),
                ('livre_annee', models.CharField(max_length=4)),
                ('livre_pages', models.IntegerField()),
            ],
        ),
    ]
