# Generated by Django 2.0.4 on 2018-04-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('SF', 'Science fiction'), ('S', 'Satire'), ('AA', 'Action and Adventure'), ('R', 'Romance'), ('M', 'Mystery'), ('H', 'Horror'), ('SH', 'Self help'), ('H', 'Health'), ('G', 'Guide'), ('HI', 'History'), ('SC', 'Science'), ('CO', 'Cookbooks')], max_length=2),
        ),
    ]
