# Generated by Django 2.0.4 on 2018-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20180425_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
            ],
        ),
    ]
