# Generated by Django 2.0.4 on 2018-04-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_sitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='twilio_account_sid',
            new_name='library_account_sid',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='twilio_auth_token',
            new_name='library_auth_token',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='twilio_phone_number',
            new_name='library_phone_number',
        ),
    ]
