# Generated by Django 2.0.4 on 2018-04-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_session_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session_Cart',
        ),
    ]
