# Generated by Django 2.0.4 on 2018-04-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_delete_session_cart'),
        ('main_site', '0005_auto_20180425_1546'),
    ]

    operations = [
    ]
